### ISSUE TITLE
Extra space under h1 and footer

### ISSUE THREAD

**Issue by jen-power** [algonquindesign-grads/2021-coming-soon#1]
@thomasjbradley 

There are two elements with extra space underneath them that I'm having trouble figuring out what the cause is.

The first is in the text in the masthead. Since the logo for this year uses alternate character features, it's displayed as an SVG rather than direct text. I figured this should be labelled as an H1 and have the alt text in the img tag, otherwise I'm not sure what else on the page would be an H1.
So in the H1 tag, there is an img tag. When I hover over the H1 element, there is extra space below the text, but it's not present when I hover over the img tag. I tried putting "push-0" onto the H1 tag but it didn't remove the space. It's also not highlighted in orange so I figure it's not a margin on the H1...I think?
<img width="1142" alt="Screen Shot 2021-01-29 at 12 36 36 PM" src="https://user-images.githubusercontent.com/43247074/106308705-1594f280-622f-11eb-83a9-4b459df3bb65.png">

The second element is the footer. When I inspect the site and hover over the footer element, there is a small bit of space at the end of the page. It doesn't appear to be a margin on footer or on body, but I'm not sure how to get rid of it.
<img width="1426" alt="Screen Shot 2021-01-29 at 12 36 56 PM" src="https://user-images.githubusercontent.com/43247074/106308836-470dbe00-622f-11eb-9d50-096aaa44dce3.png">

Also, I've committed and pushed everything. The site is basically done except for fixing up these spacing issues and adding a URL for the LinkedIn social media button (branding hasn't given me the URL yet...). Do I need to do anything else after pushing my commits so that you and the rest of the team can actually see the web page?

**Comment by thomasjbradley** [comment]
*Re: header space—*

Add `display: block` onto `.logo`—images always want to align to the text baseline, but setting `display: block` prevents that. You’ll then also need to add `margin: 0 auto` to keep it centered.

**Comment by thomasjbradley** [comment]
*Re: footer—*

Exact same problem: `display: block` on that image.

**Comment by thomasjbradley** [comment]
Everyone else should be able to see the page at the GitHub Pages URL:

https://algonquindesign-grads.github.io/2021-coming-soon/

**Comment by jen-power** [comment]
@thomasjbradley 

Perfect, thank you!
